services:
    db:
        image: postgres:17-alpine
        container_name: pft-db
        restart: always
        environment:
            POSTGRES_USER: pft_user
            POSTGRES_PASSWORD: pft_pass
            POSTGRES_DB: pft_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pft_user -d pft_db"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    redis:
        image: "redis:8.2.1-alpine"
        container_name: pft-redis
        restart: always
        ports:
            - "6379:6379"
        environment:
            REDIS_USER: redis_user
            REDIS_PASSWORD: my_redis_password
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" # Can be added to all services better for minimal docker container logs

    backend:
        build: ./backend
        container_name: pft-backend
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pft_db
            SPRING_DATASOURCE_USERNAME: pft_user
            SPRING_DATASOURCE_PASSWORD: pft_pass
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_USER: redis_user
            SPRING_REDIS_PASSWORD: my_redis_password
            SPRING_PROFILES_ACTIVE: prod
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        ports:
            - "8080:8080"
        volumes:
            - backend-logs:/app/logs
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -q --spider http://localhost:8080/actuator/health || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    frontend:
        build: ./frontend
        container_name: pft-frontend
        restart: always
        environment:
            VITE_API_BASE: http://localhost:8080/api
        ports:
            - "3000:80"
        depends_on:
            backend:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "pgrep nginx || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 20s

volumes:
    db_data:
    redis_data:
    backend-logs:
